### ISSUE TITLE
enable addressing arbitrary rdf resources in a template

### ISSUE THREAD

**Issue by FTeichmann** [white-gecko/jekyll-rdf#103]
Using [this](https://github.com/FTeichmann/Jekyll-RDF-Businesscards/blob/master/rdf-data/content.ttl) example graph, I tried to display the main Navigation on e.g. the template for foaf:Person:
```
{% assign navigation = "ex:Mainnav" %}
{% assign container = navigation.rdf | rdf_property: '<http://example.org/hasContainer>' | rdf_container %}
<ul>
{% for item in container %}
<li>{{ item }}</li>
{% endfor %}
</ul>
```
Obviously this functionality is not implemented yet and does not work, but it could be a nice addition to enable rendering of "remote" parts of the graph on every template. Using SPARQL-queries to display these contents works fine.

**Comment by Simaris** [comment]
Once #108 is merged, you also might need to correct a typo in your graph to test that feature:
  line 102 ex:hasContainer ex:Main`n`avItems .
  line 104 ex:Main`N`avItems a rdf:Bag ;
