### ISSUE TITLE
More flexible and consequent filter APIs

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#120]
This issue contradicts the solution proposed in #114 and #109 .

`sparql_query`:
- behavior on `master` is: `page.rdf | sparql_query: <query>`
- behavior on `develop` is: `<query> | sparql_query` (`page.rdf` is taken from the `Jekyll::RdfHelper`)
- behavior should be: `[<rdf_resource>] | sparql_query: <query>`
    - shortcut for `page.rdf | sparql_query: <query>` is `sparql_query: <query>` (`page.rdf` is taken from the `Jekyll::RdfHelper`)
    -  `"http://resource/" | rdf_get | sparql_query: <query>` would also be possible
    - in all cases the variable `?resourceUri` in the query is replaced/bound by the given resource (input)

`rdf_property`:
- behavior on `master` and `develop` is: `<resource> | rdf_property: <property>`
- behavior should be: `<resource> | rdf_property: <property>`
    - shortcut for `page.rdf | rdf_property: <property>` is  `rdf_property: <property>` (`page.rdf` is taken from the `Jekyll::RdfHelper`)
    -  `"http://resource/" | rdf_get | rdf_property: <query>` would also be possible (as it is now)

same for `rdf_inverse_property`

**Comment by Simaris** [comment]
Unfortunately, `{{ |rdf_property: property }} or `{{ rdf_property: property}}` are not valid expressions to jekylls liquid engine, so these short-cuts are not possible.
The closest we can realise (as far as I know) is `{{ nil | rdf_property: property }}`.

**Comment by white-gecko** [comment]
I think if this is not possible we don't need these shortcut options. Using `nil` might be confusing.
I think the only simplification would be to allow `{{ page | rdf_property: property }}` as well as `{{ page.rdf | rdf_property: property }}`.
