### ISSUE TITLE
Clarify the influence of `permalinks` setting

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#131]
If using the JekyllRDF plug-in in combination with setting `permalink: pretty` in `_config.yml` makes the `RdfResource.render_path` invalid/incorrect.

E.g. the resource `http://example.org/resource` has the following proeprties (which are as expected):

```
page.rdf.iri
    http://example.org/resource
page.rdf.render_path
    /resource.html
page.rdf.page_url
    /resource
```

but actually is rendered to `/resource/index.html`

the resource `http://example.org/anotherResource/` has the following properties (which are as expected):

```
page.rdf.iri
    http://example.org/anotherResource/
page.rdf.render_path
    /anotherResource/index.html
page.rdf.page_url
    /anotherResource/
```

but actually is rendered to `http://jekyll.docker/anotherResource/index/index.html`

More information about permalinks is available at https://jekyllrb.com/docs/permalinks/

Could you please find out, how permalinks do interfere with our architecture? And could you find a solution, how we should deal with this situation?

**Comment by white-gecko** [comment]
As is seems to me all permalinks ending with `/` (e.g. `pretty`) are causing the unwanted behavior, while all permalinks ending with `.html` (e.g. `date`, `ordinary`, `none`) or more general "not a slash" are creating the files, as we want it.

**Comment by white-gecko** [comment]
Maybe there is a way to circumvent the permalink creation for the RDF pages.

**Comment by Simaris** [comment]
It is actually possible to suppress this behaviour by letting the plugin overwrite the permalink variable for each rdf-page ( #135 )
