### ISSUE TITLE
Clarify interplay between Jekyll-Pages and Resource

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#141]
We should make sure what happens if a Jekyll-Page and a Resource are rendered to the same output file.

1. One option would be, that the content of the Jekyll-Page is rendered into the place of `{{content}}` in the selected template for the RDF-Resource.
2. Another Option is to just overwrite everything with the RDF-Resources and give the option to move "special Pages" to the `_layouts` folder and define an instance mapping in the `_config.yml`.

What is the influence on the layout selection? Will it be the layout defined in the Jekyll-Page or the one identified by the class/instance-mapping for the RDF-Resource?

**Comment by Simaris** [comment]
Well option 1 seems difficult, but possible (associated with a cost in performance scaling with the overall number of pages).

Option 2 seems very intrusive. We would change the default rendering behaviour of non RDF pages and break compatibility with other render plugins. Furthermore, what instance has to be used for mapping? And if this effects only a subset of pages, the user has to know which pages collide with RDF pages to make fitting adjustments.

so I guess option 1 would be the one to go

At last, our plugin overwrites the layout variable, so depending on how we implement it the layout identified by the class/instance-mapping will be the one in use.

**Comment by white-gecko** [comment]
This is fixed in #177 .

From now on we support option 1+:

The content of the Jekyll-Page is rendered into the place of {{content}} of the selected layout.
The layout is selected as follows:
1. if it in the layout is specified in the yaml-front-matter this is chosen
2. if no layout is specified in the yaml-front-matter the layout is selected as for all RDF resources.
