### ISSUE TITLE
how to create links between resources?

### ISSUE THREAD

**Issue by seebi** [white-gecko/jekyll-rdf#142]
according to [jekylls template documentation](https://jekyllrb.com/docs/templates/#links), the `link` tag should be used to generate links between pages.

What is the suggested way to link resources to each other?

**Comment by seebi** [comment]
ok, this worked somehow - or is there a better way?

```
  <h2>Resources linking here</h1>
{% assign query = 'SELECT ?sub ?pre WHERE { ?sub ?pre ?resourceUri }' %}
{% assign resultset = page.rdf | sparql_query: query %}
<ul>
    {% for result in resultset %}
    <li>
        <a title="{{ result.pre }}" href="{{ site.baseurl }}{{ result.sub.page_url }}">{{ result.sub | rdf_property: 'rdfs:label', 'en'}}</a>
    </li>
    {% endfor %}
</ul>
```

**Comment by seebi** [comment]
important is the dot in `{{ site.baseurl }}.{{ result.sub.page_url }}` - links to the main resource do not work ...

**Comment by white-gecko** [comment]
Actually I didn't know of the `{% link … %}` tag. So we should take this into account for a next release.

Our intended way for linking to resources within a site is to use [`resource.page_url`](https://github.com/white-gecko/jekyll-rdf#resourcepage_url) as you did in your example. For linking to resources on the web just take the resource as it is.

The dot in the URL looks strange, we have to investigate this.

**Comment by white-gecko** [comment]
Are you using the current 3.0.0 pre-release or the current stable version?
For the current stable version (2.3.0) there is no proper `page_url` support yet, for the pre-releases there might be instabilities.

**Comment by seebi** [comment]
I use the stable version

**Comment by white-gecko** [comment]
How did you set your `url` and `baseurl` in the `_config.yml`?

I've tried your example with the latest 3.0.0 pre-release, where the paths work without the dot.

**Comment by white-gecko** [comment]
Does this pullrequest satisfy your issue: https://github.com/white-gecko/jekyll-rdf/pull/199

**Comment by seebi** [comment]
@janbeckert can you validate this issue for me pls?

**Comment by white-gecko** [comment]
We have decided to reject #199. Further we have to disappoint you, that the liquid link tag does not work on variables. But we have found a solution which allows things like:

    {% link http://example.org/Homer %}

this will come in the future.
