### ISSUE TITLE
`page_url` is different to actual render location if url has a trailing slash

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#146]
The Value of `resource.page_url` is different to the actual location, to where the resource is rendered in the case, when the parameter `url` in the config has a trailing slash

    url: "http://example.com/"

    resource.page_url: rdfsites/http/example.org/ResourceA

instead of 

    resource.page_url: ResourceA

**Comment by Simaris** [comment]
it seems that the domain of the URL ends of `com` while the domain of the resource ends of `org`
