### ISSUE TITLE
page.rdf.to_s and page.rdf.iri.to_s are empty

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#160]
page.rdf.to_s and page.rdf.iri.to_s are empty

    {{page.rdf.to_s}}

**Comment by white-gecko** [comment]
Maybe we have to do something with `to_liquid`

**Comment by Simaris** [comment]
I'm not sure if work is actually necessary.
I can confirm that every time liquid uses an object like {{page.rdf}} it refers to them by `.to_liquid`.
the Problem is that `to_s` always will return a String.  Since String ist a basic class, we are not supposed to temper with it.
