### ISSUE TITLE
Is there a way to support Redirect URLS with jekyll-rdf?

### ISSUE THREAD

**Issue by RohanAsmat** [white-gecko/jekyll-rdf#186]
I have tried to use the following plugin:
https://github.com/jekyll/jekyll-redirect-from

But, it doesn't seem to create the resources! 

Is there a preferred way of doing so with jekyll-rdf?

**Comment by white-gecko** [comment]
No jekyll-rdf does not have any support for redirects. But maybe it would be a cool thing to have an additional plugin, which evaluates owl:sameAs links and generates redirect pages :-)
