### ISSUE TITLE
Scientific notation in turtle should work seamlessly

### ISSUE THREAD

**Issue by janbeckert** [white-gecko/jekyll-rdf#191]
Similar to #179 liquid math operators should work on numbers written down in scientific notation in the turtle source file (see [https://www.w3.org/TR/turtle/#abbrev](url)) as well.

Basically numbers from the turtle file should be printed out in decimal notation by default so handling them works identically independent from the notation used in the turtle source file.

**Comment by white-gecko** [comment]
Ok, so basically this concerns the xsd:double datatype:

xsd:double

    4.2E9
    "4.2E9"^^xsd:double 

Double-precision floating point values may be written as an optionally signed mantissa with an optional decimal point, the letter "e" or "E", and an optionally signed integer exponent. The exponent matches the regular expression "[+-]?[0-9]+" and the mantissa one of these regular expressions: "[+-]?[0-9]+\.[0-9]+", "[+-]?\.[0-9]+" or "[+-]?[0-9]".

@simaris can you find out, how the ruby rdf library parses literals like that?
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
