### ISSUE TITLE
Specify list of resources to render with a file

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#216]
We need a new key `restriction_file` which refers to a list of URL of resources to render. This could speed up the initial process of executing the restriction query. Further it would also circumvent limitations of sparql endpoints for the size of returned result sets.

**Comment by Simaris** [comment]
@white-gecko to clarify, is `restriction_file` supposed to further restrict `restriction` or do you want to use these keys separately?

**Comment by white-gecko** [comment]
This file should be an alternative for the restriction query
