### ISSUE TITLE
Prefixrequest before page hook

### ISSUE THREAD

**Issue by Simaris** [white-gecko/jekyll-rdf#223]
pr #222 explains this issue.
`RdfHelper.page =` is not triggered before `RdfHelper.prefixes` in project https://github.com/SmartDataAnalytics/sda.tech.git on commit 4f8c55469a0cb86016616f3730f68277aa59476e.
This is something that should not be possible.

**Comment by RohanAsmat** [comment]
Hi,
We are facing the issue, in the release 3.0.1.a. I believe it is because of this reason.

The Sparql querry is malforming for the intial/default page due to this reason. 


Thank you in advance!

Best Regards,
Muhammad Rohan Ali Asmat

**Comment by white-gecko** [comment]
I think you are referring to https://travis-ci.org/SmartDataAnalytics/sda.tech/builds/447544962?utm_source=github_status&utm_medium=notification but this is some different problem. I think it is something with the replacement of variables in the query but I think this needs some debugging.

**Comment by RohanAsmat** [comment]
@white-gecko Sure, I can do so! 
But, it have been working fine in the previous versions!

**Comment by white-gecko** [comment]
Did it work with 2.3.0 or any later versions as well? Yes, I can't tell at the moment if this a bug coming from intended API changes, which we have introduced in 3.0.0 or if it is a bug, which we have accidentally introduced in 3.0.0.

**Comment by RohanAsmat** [comment]
@white-gecko ok!  It worked well with 2.3.0.

**Comment by Simaris** [comment]
The issue is caused by files in `_posts` using the prefix feature.  Apparently posts are rendered before pages. Jekyll also knows a third content type, document. We will implement hooks for these types. That should fix the problem.
