### ISSUE TITLE
Restricting ressources in _config.yml can cause an Error during class evaluations

### ISSUE THREAD

**Issue by Simaris** [white-gecko/jekyll-rdf#25]
If the loaded ttl-file contains the ressource foaf:Person only as an object in each statement 
(some:subject rdf:type foaf:Person)
the restriction >>>SELECT ?resourceUri WHERE ?resourceUri ?p ?o <<< prevents it from being used as a class.

Subsequent Problems:
  -class becomes unaviable for subclass relationships
  -template mapping throws an error if a mapping is defined for such a class
  -might be part of #19

**Comment by white-gecko** [comment]
Done in #28 resp. #35
