### ISSUE TITLE
foafName can potentially cause an infine loop

### ISSUE THREAD

**Issue by Simaris** [white-gecko/jekyll-rdf#27]
if two statements of the form:

plh:TPerson foaf:name sim:Homer.
sim:Homer foaf:name plh:TPerson .

are included in your rdf source file, jekyll-rdf possibly crashes because the method foafName of /lib/jekyll-rdf/drops/rdf_ressource.rb gets caught in a loop.

**Comment by white-gecko** [comment]
Related to #29 and #6

**Comment by white-gecko** [comment]
Closed by #29 resp. #42
