### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by Simaris** [white-gecko/jekyll-rdf#37]
There should be features that expose automatically the URIs hosted on the current sites. Features that check if a certain URI is hosted, list all hosted URIs and return to a given string all Similar URIs available.
Otherwise other web developers that want to access these resources would be dabbling in the dark every time they search for unknown URIs (e.g. a dev knows that we host a resource to The Simpsons, but he doesn't necessarily  know that its URI is http://www.ifi.uio.no/INF3580/simpsons#TheSimpsons)

**Comment by white-gecko** [comment]
You say, something like a sitemap? This should not directly be in the focus of jekyll-rdf and there could be solutions for jekyll already.
