### ISSUE TITLE
Show Warning if jekyll-rdf is not configured

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#40]
Currently Jekyll fails with

    jekyll 3.3.0 | Error:  key not found: "jekyll_rdf"

if jekyll-rdf is included but not configured.

There should be a warning "You've included Jekyll-RDF, but it is not configured."

**Comment by RohanAsmat** [comment]
I am getting the following error:
`You've included Jekyll-RDF, but it is not configured.`

It is while trying to install it in a new project template.

Can I ask what exactly are the configuration steps for the jekyll-rdf?

As for what I did are the following:
1) Was to install the gem
2) include in the config file
3) add the following in the config file:
jekyll_rdf:
    path: "rdf-data/sda.tech.ttl"
    language: "en"
    include_blank: true
    restriction: "SELECT ?s WHERE { ?s ?p ?o}"
    default_template: "default.html"
    class_template_mappings:
      "http://xmlns.com/foaf/0.1/Person": "page.html"
    instance_template_mappings:
      "http://www.ifi.uio.no/INF3580/simpsons#Abraham": "abraham.html"
