### ISSUE TITLE
Manual: Integrate with Jekyll does not work without template

### ISSUE THREAD

**Issue by FTeichmann** [white-gecko/jekyll-rdf#49]
Trying to follow the Manual I get for step 3: Integrate with Jekyll
```
$ jekyll build
Configuration file: /home/franz/workspace/jekyll-rdf/my_page/_config.yml
               Source: /home/franz/workspace/jekyll-rdf/my_page
               Destination: /home/franz/workspace/jekyll-rdf/my_page/_site
               Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.1.0 | Error:  no implicit conversion of nil into String
```

Do I need a mandatory mapping template (default template) to run jekyll build?

**Comment by Simaris** [comment]
Currently, you need a default template to build a jekyll site, so jekyll can render really any given resource. I don't know, whether we will change this or not, but we should definitely build in a warning for such missing configurations.

An empty .html file as a default liquid template should be enough to circumvent this error.
