### ISSUE TITLE
No Error Message for malformed config (tabs & spaces)

### ISSUE THREAD

**Issue by FTeichmann** [white-gecko/jekyll-rdf#57]
Having a malformed config file by e.g. not properly intending the lines (using spaces) for jekyll-rdf on the first level leads to:

```
Incremental build: disabled. Enable with --incremental
      Generating... 
Configuration file: /home/franz/workspace/jekyll-rdf/my_page/_config.yml
jekyll 3.1.0 | Error:  undefined method `key?' for nil:NilClass
```
On the second level the configuration has no effect and throws no error message.
[example (Line 25 ignored)](https://gist.github.com/FTeichmann/2b8cb199b52c32639e9686339d2a9a1f)

**Comment by white-gecko** [comment]
The config is parsed by jekyll, so we can't change this.
