### ISSUE TITLE
# hosting triggers without a template mapping

### ISSUE THREAD

**Issue by Simaris** [white-gecko/jekyll-rdf#59]
given two URIs:
<http://www.ifi.uio.no/INF3580/simpsons#Homer>
<http://www.ifi.uio.no/INF3580/simpsons#Marge>

if also <http://www.ifi.uio.no/INF3580/simpsons> is in the graph, the two URIs above wont be rendered on their own, even if the configuration doesn't map a suitable template for <http://www.ifi.uio.no/INF3580/simpsons>.

jekyll-rdf should do that only if <http://www.ifi.uio.no/INF3580/simpsons> has a specified template

**Comment by white-gecko** [comment]
I think the behavior you are describing is the intended behavior.
