### ISSUE TITLE
* makes queries useless

### ISSUE THREAD

**Issue by Simaris** [white-gecko/jekyll-rdf#61]
the sparql client used by jekyll-rdf (and thus the sparql_query filter) can't process the following Query:
```
SELECT ?x 
WHERE{ 
    <http://www.ifi.uio.no/INF3580/simpson-collection#Collection> <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest>* ?o. 
}
```
but it is able to process:
```
SELECT ?x 
WHERE{ 
    <http://www.ifi.uio.no/INF3580/simpson-collection#Collection> <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> ?o. 
}
```
The Problem here is not that the Query fails. Infact, it actually returns the expected number of Solutions. But these Solutions have no variables bound to them, making them effectively empty.

**Comment by white-gecko** [comment]
Could you please check with the latest sparql library and else file an issue? https://github.com/ruby-rdf/sparql

**Comment by white-gecko** [comment]
Related to #62

**Comment by Simaris** [comment]
So, I actually came to test the Problem in a separated Project and confirmed it to be a bug.
The issue can be found here: https://github.com/ruby-rdf/sparql/issues/27
and is already solved.

**Comment by white-gecko** [comment]
So could you forward our dependency version number of ruby-rdf?

**Comment by Simaris** [comment]
The gem update isn't out yet so we have to use the git repo as a dependencie for now.
The dependencies already get updated in #63.
