### ISSUE TITLE
Fails if no default_template is configured

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#64]
Jekyll fails with the message:

    jekyll 3.3.0 | Error:  no implicit conversion of nil into String

if no `default_template` is configured in `_config.yml`. The stack trace points to:

    …/jekyll-3.3.0/lib/jekyll/convertible.rb:40:in `join': no implicit conversion of nil into String (TypeError)
	from …/jekyll-3.3.0/lib/jekyll/convertible.rb:40:in `read_yaml'
	from …/jekyll-rdf-2.0.0/lib/jekyll/rdf_page_data.rb:48:in `initialize'
	from …/jekyll-rdf-2.0.0/lib/jekyll/rdf_main_generator.rb:109:in `new'
	from …/jekyll-rdf-2.0.0/lib/jekyll/rdf_main_generator.rb:109:in `block in generate'
	from …/jekyll-rdf-2.0.0/lib/jekyll/rdf_main_generator.rb:99:in `each'
	from …/jekyll-rdf-2.0.0/lib/jekyll/rdf_main_generator.rb:99:in `generate'
	from …/jekyll-3.3.0/lib/jekyll/site.rb:174:in `block in generate'
	from …/jekyll-3.3.0/lib/jekyll/site.rb:172:in `each'
        …

**Comment by Simaris** [comment]
I encountered a similar error. Therefore it might be fixed in 92e91d4dbb4bb9c9008fd93d1500031ee92e8b31 of #63.

**Comment by Simaris** [comment]
It seems like 554ad2a449b75469ed6fb34a51b5c9f4991fcf46 already fixed that bug.
Please confirm
