### ISSUE TITLE
Resources with Umlaut in the URI are rendered to rdfsites/blanknode/

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#65]
Resources with Umlaut (üöä) in the URI are rendered to `…/rdfsites/blanknode/` but they should be rendered to the normal location.

E.g. `http://example.org/Sören` is rendered to `http://localhost:4000/rdfsites/blanknode/http_D/example.org/Sören/index.html`.
It should be `http://localhost:4000/Sören/index.html`

**Comment by Simaris** [comment]
This happens because the underling URI lib does not recognizes äöüß as legit characters. In its current state jekyll-rdf would it actually place in http://localhost:4000/rdfsites/invalides/http_D/example.org/Sören/index.html
