### ISSUE TITLE
Stacktrace parameter in _config.yml

### ISSUE THREAD

**Issue by Simaris** [white-gecko/jekyll-rdf#67]
Currently, we have some filters (e.g. rdf_sparql_query) that catch eventual exception.
We should  implement a parameter (developer-mode) that allows other developer to see the stacktrace of said exceptions.

**Comment by white-gecko** [comment]
The configuration of the log output level should be aligned with the log levels of Jekyll

**Comment by white-gecko** [comment]
Depends on #145

**Comment by white-gecko** [comment]
@Simaris do you think this is still relevant?

**Comment by Simaris** [comment]
it is but not as extensive as I thought it would be when I wrote it
