### ISSUE TITLE
Jekyll-RDF Variable Comparison Bug

### ISSUE THREAD

**Issue by FTeichmann** [white-gecko/jekyll-rdf#72]
I encountered a bug when I tried to compare an assigned Jekyll Variable to Jekyll-RDF Page Variables.

example Graph:
https://gist.github.com/FTeichmann/790a65370e40582867cb9f8eb1c13672

example Layout:
https://gist.github.com/FTeichmann/062e7ac585e3daca6e6ad532d24b1518

As the workaround with `{% assign variable1 = page.rdf.iri | downcase %}` suggests, there may be a problem with the datatype.

**Comment by white-gecko** [comment]
@Simaris can you reproduce this behavior with the latest develop branch?

**Comment by Simaris** [comment]
@FTeichmann you guess about datatypes is correct.
`result.resource` has the same object type as `page.rdf`, while `page.rdf.iri` is a string.
A better workaround would be 
```
{% if page.rdf.iri == result.resource.iri %}
  This is me!
{% endif %}
```

**Comment by white-gecko** [comment]
If I understand it correctly 

    {% if page.rdf == result.resource %}
      This is me!
    {% endif %}

should work as well?

**Comment by Simaris** [comment]
No that wouldn't work because we didn't implement a .equal? method.

**Comment by white-gecko** [comment]
Ok, so we could implement an .equal? method in some future release.
