### ISSUE TITLE
Jekyll-RDF not useable on default page

### ISSUE THREAD

**Issue by FTeichmann** [white-gecko/jekyll-rdf#73]
Using [this](https://gist.github.com/FTeichmann/36cf9d991b166326692dbd82e5d5d025) configuration, I have trouble displaying anything from the graph on the default (landing) page.

Even obviously malformed SPARQL like below results in no error and no output at all.
```        
        {% capture query %}
        SELECT ?position WHERE{
            this is no correct SPARQL!
        }
        {% endcapture %}
        {% assign resultset = page.rdf | sparql_query: query %}
        {% for result in resultset %}
        {{ result.test }}
        {% endfor %}
```
Normal liquid syntax can be used and is evaluated as expected.

**Comment by white-gecko** [comment]
Actually RDF is usable. The issue is, that no `page.rdf` was present because the respective resource was not present in the RDF-Model so it was not rendered using Jekyll-RDF.
