### ISSUE TITLE
Distinguish between the term types

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#84]
We need some possibility to distinguish whether a variable/rdf_term is a literal or a resource.

**Comment by white-gecko** [comment]
Is

    {% if node.iri %}
    <li>Resource: <a href="{{ node.page_url }}">{{ node | rdf_property: "<http://www.w3.org/2000/01/rdf-schema#label>" }}</a></li>
    {% else %}
    <li>Literal: {{ node }}</li>
    {% endif %}

the way this should be achieved?

**Comment by Simaris** [comment]
i think we can use page.rdf.class to do this
but maybe we should implement a method that returns a boolean instead

**Comment by white-gecko** [comment]
But do you think my suggestion (https://github.com/white-gecko/jekyll-rdf/issues/84#issuecomment-316315996) is also a good solution? If so we can just add it to some examples section to the README and then we are fine.

**Comment by Simaris** [comment]
I'm pretty sure that if we come to the else case, the method .iri wont be defined and liquid will throw an error, causing jekyll to abort renderprocedure.

**Comment by white-gecko** [comment]
{% if node.iri %}
    <li>Resource: <a href="{{ node.page_url }}">{{ node | rdf_property: "<http://www.w3.org/2000/01/rdf-schema#label>" }}</a></li>
    {% else %}
    <li>Literal: {{ node }}</li>
    {% endif %}

Is our recommended way of distinguishing term types.
