### ISSUE TITLE
render_path is empty for resource, which is not page.rdf

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#85]
The property `render_path` of an RdfResource is empty, if it is not the `page.rdf` resource.

MWE:

graph:

    <http://example.org/Resource> <http://example.org/rel> <http://example.org/RelatedResource> .
    <http://example.org/RelatedResource> <http://example.org/rel> <http://example.org/RelatedResource> .

template:

    {% assign rel = page.rdf | rdf_property: '<http://example.org/rel>' %}
    {{ rel.render_path }}

actual:
nothing

expected:

    http://example.org/RelatedResource

**Comment by white-gecko** [comment]
Please also add a test for this

**Comment by Simaris** [comment]
it is somewhat intended behaviour since resources that are not used as page resources are not rendered. render_path is also somewhat redundant since page_url and render_path are currently nearly the same.

**Comment by white-gecko** [comment]
The difference between `page_url` and `render_path` is also depicted in #94 .

**Comment by white-gecko** [comment]
Closed by #101
