### ISSUE TITLE
page_url is not always correct

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#86]
graph:

    <http://example.org/Resource> <http://example.org/rel> <http://example.org/RelatedResource> .
    <http://example.org/RelatedResource> <http://example.org/rel> <http://example.org/RelatedResource> .

template

```
<dl>
    <dt>render_path</dt>
    <dd><pre>{{ page.rdf.render_path }}</pre></dd>
    <dt>page_url</dt>
    <dd><pre>{{ page.rdf.page_url }}</pre></dd>
    <dt>iri</dt>
    <dd><pre>{{ page.rdf.iri }}</pre></dd>
</dl>

rel:
{% assign rel = page.rdf | rdf_property: '<http://example.org/rel>' %}
<dl>
    <dt>render_path</dt>
    <dd><pre>{{ rel.render_path }}</pre></dd>
    <dt>page_url</dt>
    <dd><pre>{{ rel.page_url }}</pre></dd>
    <dt>iri</dt>
    <dd><pre>{{ rel.iri }}</pre></dd>
</dl>
```

actual:

```
render_path

    Resource/index.html

page_url

    /Resource/

iri

    http://example.org/Resource

rel:

render_path

page_url

    /Resource/

iri

    http://example.org/RelatedResource
```

expected:
```
render_path

    Resource/index.html

page_url

    /Resource/

iri

    http://example.org/Resource

rel:

render_path

    RelatedResource/index.html

page_url

    /RelatedResource/

iri

    http://example.org/RelatedResource
```

**Comment by white-gecko** [comment]
The missing `render_path` is covered in #85

**Comment by white-gecko** [comment]
please also add a test for this

**Comment by Simaris** [comment]
the problem is that page_url is supposed to point at the page it is used on. Changing that behaviour would be an API change (That behaviour is actually used in code). We could implement another method to give the expected information and update behaviours in our next mayor patch.

**Comment by white-gecko** [comment]
Since the method is only used inside the jekyll-rdf code it is no API change. The difference between `page_url` and `render_path` is also depicted in #94 .

**Comment by white-gecko** [comment]
Since #101 it is now:


```
render_path

    Resource/index.html

page_url

    Resource/

iri

    http://example.org/Resource

rel:

render_path

    rdfsites/http/example.org/RelatedResource/index.html

page_url

    rdfsites/http/example.org/RelatedResource/

iri

    http://example.org/RelatedResource
```

even though both pages are under the base url `http://example.org/`
