### ISSUE TITLE
NoMethodError if a class is configured that does not appear in the source file

### ISSUE THREAD

**Issue by Simaris** [white-gecko/jekyll-rdf#97]
if we change
```
...
jekyll_rdf:
  ...
  class_template_mappings:
    "http://pcai042.informatik.uni-leipzig.de/~dtp16#SimpsonPerson" : "simpsonPerson.html"
  ...
```
to
```
...
jekyll_rdf:
  ...
  class_template_mappings:
    "http://pcai042.informatik.uni-leipzig.de/~dtp16/#SimpsonPerson" : "simpsonPerson.html"
  ...
```
a NoMethodError accures since `http://pcai042.informatik.uni-leipzig.de/~dtp16/#SimpsonPerson` is not in our ttl

**Comment by RohanAsmat** [comment]
both of the code blocks appear same, what is the difference ?

**Comment by Simaris** [comment]
there is a `/` before `#` in `http://pcai042.informatik.uni-leipzig.de/~dtp16/#SimpsonPerson`

the source of this problem is already known
this issue serves more as an reminder to fix it

**Comment by white-gecko** [comment]
Mappings of RDF classes to templates should just be ignored, if the according class is not used in the provided model.
Maybe there could be some info output, it jekyll is started with verbose parameter `jekyll build --verbose`
